/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2024-10-18 05:34:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginMC_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>E - Toilet</title>\r\n");
      out.write("    <!-- meta tags -->\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <meta name=\"keywords\" content=\"Art Sign Up Form Responsive Widget, Audio and Video players, Login Form Web Template, Flat Pricing Tables, Flat Drop-Downs, Sign-Up Web Templates, \r\n");
      out.write("\t\tFlat Web Templates, Login Sign-up Responsive Web Template, Smartphone Compatible Web Template, Free Web Designs for Nokia, Samsung, LG, Sony Ericsson, Motorola Web Design\"\r\n");
      out.write("    />\r\n");
      out.write("    <!-- /meta tags -->\r\n");
      out.write("    <!-- custom style sheet -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <!-- /custom style sheet -->\r\n");
      out.write("    <!-- fontawesome css -->\r\n");
      out.write("    <link href=\"css/fontawesome-all.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- /fontawesome css -->\r\n");
      out.write("    <!-- google fonts-->\r\n");
      out.write("    <link href=\"//fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("    <!-- /google fonts-->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function validateEmail(emailField)\r\n");
      out.write("{\r\n");
      out.write("\tvar reg = /^([A-Za-z0-9_\\-\\.])+\\@([A-Za-z0-9_\\-\\.])+\\.([A-Za-z]{2,4})$/;\r\n");
      out.write("    if (reg.test(emailField.value) == false) \r\n");
      out.write("    {\r\n");
      out.write("        alert('Invalid Email Address');\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("    return true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <h1 style=\"color:orange; text-shadow: 0.5px 0.5px 0.5px red;\">E - Toilet</h1>\r\n");
      out.write("    <div class=\" w3l-login-form\">\r\n");
      out.write("        <h2 style=\"color:red; text-shadow: 0.5px 0.5px 0.5px white;\">Municipal Corporation Login</h2>\r\n");
      out.write("        <form action=\"loginMC\" method=\"POST\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\" w3l-form-group\">\r\n");
      out.write("                <label>SR.NO:</label>\r\n");
      out.write("                <div class=\"group\">\r\n");
      out.write("                    <i class=\"fas fa-user\"></i>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" placeholder=\"SR Number\" name=\"srno\" required=\"required\" />\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\" w3l-form-group\">\r\n");
      out.write("                <label>Password:</label>\r\n");
      out.write("                <div class=\"group\">\r\n");
      out.write("                    <i class=\"fas fa-unlock\"></i>\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" placeholder=\"Password\" name=\"passwd\" required=\"required\" />\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <button type=\"submit\" style=\"color:rgb(248, 204, 114); text-shadow: 0.5px 0.5px 0.5px red;\">Login</button>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <div class=\"col-sm-offset-5 col-sm-10\" style=\"color:yellow;\">\r\n");
      out.write("                    Admin Login? <a href=\"index.jsp\"><font color=\"white\">Click Here</font> </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
