/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2024-10-18 05:40:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class MCpanel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("      <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>E - Toilet</title>\r\n");
      out.write("\t<!-- BOOTSTRAP STYLES-->\r\n");
      out.write("    <link href=\"assets/css/bootstrap.css\" rel=\"stylesheet\" />\r\n");
      out.write("     <!-- FONTAWESOME STYLES-->\r\n");
      out.write("    <link href=\"assets/css/font-awesome.css\" rel=\"stylesheet\" />\r\n");
      out.write("        <!-- CUSTOM STYLES-->\r\n");
      out.write("    <link href=\"assets/css/custom.css\" rel=\"stylesheet\" />\r\n");
      out.write("     <!-- GOOGLE FONTS-->\r\n");
      out.write("   <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("   \tfunction access(){\r\n");
      out.write("\t\t");
 Object s1 = request.getSession().getAttribute("msg");
		 if(s1!=null){ 
      out.write("\r\n");
      out.write("\t\talert('");
      out.print(s1.toString());
      out.write("');\r\n");
      out.write("\t\t");
 request.getSession().setAttribute("msg",null);
		}	
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("   \t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"access()\">\r\n");

//AbstractDao abstractDao=new AbstractDao();

      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("        <nav class=\"navbar navbar-default navbar-cls-top \" role=\"navigation\" style=\"margin-bottom: 0\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".sidebar-collapse\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a class=\"navbar-brand\" style=\"font-size:19px\" href=\"#\">E - Toilet</a> \r\n");
      out.write("            </div>\r\n");
      out.write("  <div style=\"color: white;\r\n");
      out.write("padding: 15px 50px 5px 50px;\r\n");
      out.write("float: right;\r\n");
      out.write("font-size: 16px;\"> &nbsp; <a href=\"loginMC.jsp\" class=\"btn btn-danger square-btn-adjust\">Logout</a> </div>\r\n");
      out.write("            </nav>   \r\n");
      out.write("            <!-- /. NAV TOP  -->\r\n");
      out.write("            <nav class=\"navbar-default navbar-side\" role=\"navigation\">\r\n");
      out.write("            <div class=\"sidebar-collapse\">\r\n");
      out.write("             <ul class=\"nav\" id=\"main-menu\">\r\n");
      out.write("\t\t\t\t<li class=\"text-center\">\r\n");
      out.write("            <img src=\"assets/img/find_user.png\" class=\"user-image img-responsive\" style=\"height: 100px;\"/>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t  <li>\r\n");
      out.write("                        <a  href=\"MCpanel.jsp\"><i class=\"fa fa-home fa-3x\"></i>Home</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("\t\t\t\t  <li>\r\n");
      out.write("                        <a  href=\"addToilet.jsp\"><i class=\"fa fa-edit fa-3x\"></i>Add Toilet</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a  href=\"viewcleaninglogs.jsp\"><i class=\"fa fa-table fa-3x\"></i>View Toilets</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a  href=\"viewuncleanedtoilet.jsp\"><i class=\"fa fa-table fa-3x\"></i>View Uncleaned Toilets</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("\t                </ul>\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("            </nav>  \r\n");
      out.write("        <!-- /. NAV SIDE  -->\r\n");
      out.write("        \r\n");
      out.write("      <div id=\"page-wrapper\" >\r\n");
      out.write("            <div id=\"page-inner\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("<!--          \t\t<h2>&nbsp&nbspMunicipal Corporation panel</h2>\r\n");
      out.write(" -->         \t\t\r\n");
      out.write("          \t\t<img src=\"images/adminpanel.webp\" style=\"width:100%;height:100%\">\r\n");
      out.write("  <div class=\"col-md-12\">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("     \r\n");
      out.write("\t\t\t\t\t                    </div>                                           \r\n");
      out.write("                                         \r\n");
      out.write("                    </div>\r\n");
      out.write("               \r\n");
      out.write("           \r\n");
      out.write("             <!-- /. PAGE INNER  -->\r\n");
      out.write("            </div>\r\n");
      out.write("         <!-- /. PAGE WRAPPER  -->\r\n");
      out.write("        </div>\r\n");
      out.write("     <!-- /. WRAPPER  -->\r\n");
      out.write("    <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->\r\n");
      out.write("    <!-- JQUERY SCRIPTS -->\r\n");
      out.write("    <script src=\"assets/js/jquery-1.10.2.js\"></script>\r\n");
      out.write("      <!-- BOOTSTRAP SCRIPTS -->\r\n");
      out.write("    <script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- METISMENU SCRIPTS -->\r\n");
      out.write("    <script src=\"assets/js/jquery.metisMenu.js\"></script>\r\n");
      out.write("      <!-- CUSTOM SCRIPTS -->\r\n");
      out.write("    <script src=\"assets/js/custom.js\"></script>\r\n");
      out.write("    <SCRIPT language=Javascript>\r\n");
      out.write("     function isNumberKey(evt)\r\n");
      out.write("{\r\n");
      out.write("var charCode = (evt.which) ? evt.which : event.keyCode;\r\n");
      out.write("\r\n");
      out.write("if (charCode > 31 && (charCode<48 || charCode>57))\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t\r\n");
      out.write("return true;\r\n");
      out.write("}\r\n");
      out.write("       \r\n");
      out.write("</SCRIPT>\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
